# 没用上
vqvae:
  base_lr: 1e-4
  params:
    spatial_dims: 3
    in_channels: 1
    out_channels: 1
    channels: (64, 64)  # 原为 (256, 256)
    num_res_channels: 64  # 原为 256
    num_res_layers: 1  # 原为 2
    downsample_parameters: ((2, 2, 1, 1), (2, 2, 1, 1)) # 减小 stride 和 kernel
    upsample_parameters: ((2, 2, 1, 1, 0), (2, 2, 1, 1, 0))
    num_embeddings: 128  # 原为 256
    embedding_dim: 16  # 原为 32